import * as React from "react";
import { createContext, useEffect, useState, useContext } from "react";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import Divider from "@mui/material/Divider";
import DeleteIcon from "@mui/icons-material/Delete";
import EditIcon from "@mui/icons-material/Edit";
import AddIcon from "@mui/icons-material/Add";
import {
  Avatar,
  IconButton,
  ListItemAvatar,
  ListItemButton,
} from "@mui/material";
import axios from "axios";
import { apiurls } from "../constants/apiurls";
import AuthContext from "../context/AuthContex";

const style = {
  p: 0,
  width: "100%",
  maxWidth: 360,
  borderRadius: 2,
  border: "1px solid",
  borderColor: "divider",
  backgroundColor: "background.paper",
};

function ToDoList() {
  const messages = [
    {
      id: 1,
      primary: "Brunch this week?",
      secondary:
        "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 2,
      primary: "Birthday Gift",
      secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 3,
      primary: "Recipe to try",
      secondary:
        "I am try out this new BBQ recipe, I think this might be amazing",
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 4,
      primary: "Yes!",
      secondary: "I have the tickets to the ReactConf for this year.",
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary:
        "My appointment for the doctor was rescheduled for next Saturday.",
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 6,
      primary: "Discussion",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 7,
      primary: "Summer BBQ",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 8,
      primary: "Discussion",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
              navigation drawer or overflow menu) open as bottom sheets at a higher elevation
              than the bar.`,
      person: "https://pc.net/img/terms/avatar.svg",
    },
    {
      id: 9,
      primary: "Summer BBQ",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
              for my backyard and would love to fire up the grill.`,
      person: "https://pc.net/img/terms/avatar.svg",
    },
  ];
  const [todoList, setTodoList] = useState([]);
  const { currentUser } = useContext(AuthContext);
  useEffect(() => {
    axios
      .get(apiurls.TodoApi + currentUser.user_id, {
        headers: {
          Authorization: currentUser.token,
        },
      })
      .then(function (response) {
        console.log(response);
        setTodoList(response.data);
      })
      .catch(function (error) {
        console.log(error);
      });
  }, []);
  const handleDelete = (todo_id) => {
    axios
      .delete(apiurls.TodoApi + currentUser.user_id + "/" + todo_id, {
        headers: {
          Authorization: currentUser.token,
        },
      })
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
  };
  return (
    <List sx={{ mb: 2 }}>
      {todoList.map(({ user_id, body, image_upload, file_upload, todo_id }) => (
        <React.Fragment key={user_id}>
          <ListItemButton>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={image_upload} />
            </ListItemAvatar>
            <ListItemText
              primary={body}
              secondary={
                file_upload ? (
                  <a
                    href={file_upload}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Attached file
                  </a>
                ) : (
                  ""
                )
              }
            />
            <IconButton edge="end" aria-label="edit">
              <EditIcon />
            </IconButton>
            <IconButton
              edge="end"
              aria-label="delete"
              onClick={() => handleDelete(todo_id)}
            >
              <DeleteIcon />
            </IconButton>
          </ListItemButton>
          <Divider component="li" />
        </React.Fragment>
      ))}
    </List>
  );
}

export default ToDoList;
